[Service]
  Host = "192.168.86.21"
  Port = 49991
  ConnectRetries = 3
  HealthCheck = ""
  StartupMsg = "device RPI started"
  ReadMaxLimit = 256
  Timeout = 5000

[Clients]
  [Clients.Data]
    Host = "192.168.86.32"
    Port = 48080

  [Clients.Metadata]
    Host = "192.168.86.32"
    Port = 48081

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
  RemoteURL = ""
  File = "-"

[[DeviceList]]
  Name = "RPiMotionDetector"
  Profile = "RPi_Motion_Detector"
  Description = "Motion detector using RPi's GPIO pins and a PIR sensor"
  Labels = [ "RPi Example" ]
  [DeviceList.Protocols.GPIO]
    Address = "GPIO"
  [[DeviceList.AutoEvents]]
    Frequency="1s"
    OnChange = false
    Resource = "Get_MotionState"
