[Service]
  Host = "192.168.86.143"
  Port = 49991
  ConnectRetries = 3
  HealthCheck = ""
  StartupMsg = "device RPI started"
  ReadMaxLimit = 256
  Timeout = 5000

[Clients]
  [Clients.Data]
    Host = "192.168.86.32"
    Port = 48080

  [Clients.Metadata]
    Host = "192.168.86.32"
    Port = 48081

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
  RemoteURL = ""
  File = "-"

[[DeviceList]]
  Name = "RPiBlinkLed"
  Profile = "RPi_Blink_Led"
  Description = "LED control using RPi's GPIO pins"
  Labels = [ "RPi Example" ]
