FROM alpine:3.8 as builder
MAINTAINER Michael Hall <mhall@gmail.com>
RUN apk add --update --no-cache build-base git gcc cmake make linux-headers yaml-dev libmicrohttpd-dev curl-dev

COPY scripts /device-rpi/scripts
COPY src /device-rpi/src/
RUN mkdir -p /device-rpi/build

WORKDIR /device-rpi
RUN /device-rpi/scripts/build_deps.sh
RUN /device-rpi/scripts/build.sh

FROM alpine:3.8

RUN apk add --update --no-cache linux-headers yaml libmicrohttpd curl-dev

COPY --from=builder /device-rpi/build/release/device-rpi /device-rpi/build/release/
COPY --from=builder /usr/lib/libcsdk.so /usr/lib
COPY --from=builder /usr/include/edgex /usr/include/edgex
COPY --from=builder /usr/include/thpool.h /usr/include/thpool.h
COPY --from=builder /usr/include/iot /usr/include/iot
COPY --from=builder /usr/local/include/mraa /usr/local/include/
COPY --from=builder /usr/local/include/mraa.h /usr/local/include/
COPY --from=builder /usr/local/lib/libmraa.so* /usr/local/lib/

COPY LICENSE /device-rpi/
COPY res /device-rpi/res/
COPY examples /device-rpi/examples

ENTRYPOINT ["/device-rpi/build/release/device-rpi", "-c"]
CMD ["/device-rpi/res/"]
